### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by arshiamohammdii** [xyfir/gitpw#3]
Why would you want to encrypt git repositories?

**Comment by MrXyfir** [comment]
Git is amazing for version control and syncing data manually between machines. I think it's a useful tool for more than just code.

For example, I store my own personal notes in Git. The main problem at least for me with regards to using Git to store notes is the lack of encryption. There are some other solutions for encryption within Git but none of them worked the way I wanted them to.

This is still a work in progress but I see it eventually being the foundation for other tools that utilize Git for syncing and tracking changes in sensitive data that should be encrypted. Imagine a notes app, a password manager, etc.
